# PROVAVEL QUESTÃO DUPLICADA, CORRIGIR DPS

from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
from random import choice
import time

# This secure connect bundle is autogenerated when you download your SCB,
# if yours is different update the file name below
cloud_config = {"secure_connect_bundle": "secure-connect-xlunar.zip"}

# This token JSON file is autogenerated when you download your token,
# if yours is different update the file name below
with open("xlunar-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]
KEYSPACE = "xlunar"

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
with cluster.connect() as session:

    # --------------------------------------------------------------------------------------------
    # CRIAR A TABELA DE QUESTOES

    # session.execute(
    #     f"""
    # CREATE TABLE {KEYSPACE}.questoes (
    #     id UUID PRIMARY KEY,
    #     numero INT,
    #     ano INT,
    #     semestre INT,
    #     imagem TEXT,
    #     alternativas LIST<TEXT>,
    #     alternativa_correta INT,
    #     materia TEXT,
    #     enunciado TEXT
    # );
    # """
    # )

    # --------------------------------------------------------------------------------------------
    # MANDAR QUESTOES

    # with open("questoes.tsv", encoding="utf-8") as file:
    #     for i, linha in enumerate(file):
    #         (
    #             numero,
    #             ano,
    #             semestre,
    #             imagem,
    #             alternativas,
    #             alternativa_correta,
    #             materia,
    #             enunciado,
    #         ) = linha.split("|")
    #         comando = f"""INSERT INTO {KEYSPACE}.questoes (id, numero, ano, semestre, imagem, alternativas, alternativa_correta, materia, enunciado)
    # VALUES (uuid(), {numero}, {ano}, {semestre}, '{imagem}', {alternativas.split("$")}, {alternativa_correta}, '{materia}', '{enunciado}');"""
    #         session.execute(comando)
    #         print(i + 1)
    #     print("pronto")

    # --------------------------------------------------------------------------------------------
    # PRINTAR TODOS OS ENUNCIADOS

    # a = session.execute(
    #     f"""
    # SELECT * FROM {KEYSPACE}.usuarios
    #     """
    # )

    # for row in a:
    #     print(row.canal_id)
    #     print()

    # --------------------------------------------------------------------------------------------
    # CONTADOR DE QUESTOES

    # numero_de_questoes = session.execute(
    #     f"SELECT COUNT(*) FROM {KEYSPACE}.usuarios"
    # ).one()
    # print(numero_de_questoes)

    # --------------------------------------------------------------------------------------------

    # CRIAR A TABELA DE USUARIOS

    # session.execute(
    #     f"""
    # CREATE TABLE {KEYSPACE}.usuarios (
    #     id UUID PRIMARY KEY,
    #     discord_id TEXT,
    #     nome_exibicao TEXT,
    #     nome_usuario TEXT,
    #     pontuacao INT,
    #     questoes_acertadas LIST<UUID>,
    #     questoes_erradas LIST<UUID>,
    #     canal_id TEXT
    # );
    # """
    # )

    # --------------------------------------------------------------------------------------------

    #

    # questoes_acertadas = session.execute(
    #     f"SELECT questoes_acertadas FROM xlunar.usuarios WHERE discord_id = '766039963736866828' ALLOW FILTERING"
    # ).one()
    # print(questoes_acertadas)

    # --------------------------------------------------------------------------------------------

    pass
